### ISSUE TITLE
Tools Suggestions

### ISSUE THREAD

**Issue by davidhund** [jenniferlynparsons/awesome-writing#2]
Thanks a lot Jennifer!

I wonder if you've come across [alexjs.com](http://alexjs.com):

> alex helps you find gender favouring, polarising, race related, religion inconsiderate, or other unequal phrasing.

Also: I've build a tiny text 'linter', as a retext plugin [retext](https://github.com/retextjs/retext) (a a natural language processor in JavaScript) that warns us of using language such as 'just' or 'simply': 

https://github.com/davidhund/retext-assuming

**Comment by jenniferlynparsons** [comment]
oh those are great resources!!! i saw your tweet about them and was going to add them, now they're nice and handy here. thanks so much for sharing them!
